### ISSUE TITLE
If UVMap does not exists.

### ISSUE THREAD

**Issue by mifth** [nutti/Copy-And-Paste-UV_Blender-Ext#7]
Hi.

If i try to copy UVs from one object to another - i get an exception if the object does not have UVMap.
Could you check if UVMap exists?

And if it does not exists - either make error message or create new UVMap.

**Comment by nutti** [comment]
Thanks for your report.

I'll fix this problem this weekend.

**Comment by nutti** [comment]
I fixed this problem.
Please check newest plugin.

**Comment by mifth** [comment]
Fixed! Thank you a lot!
